// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'radio.dart';

Future<void> aDummyFunctionToMakeFrbGenerateTheTypes({
  required CarIdentity identity,
  required CarPhysics physics,
  required ClientMessage clientMessage,
  required ServerMessage serverMessage,
}) => RustLib.instance.api
    .crateApiTelemetryADummyFunctionToMakeFrbGenerateTheTypes(
      identity: identity,
      physics: physics,
      clientMessage: clientMessage,
      serverMessage: serverMessage,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientMessage>>
abstract class ClientMessage implements RustOpaqueInterface {}
