[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"

[target.thumbv7em-none-eabihf]
linker = "arm-none-eabi-gcc"

[alias]
build-powertrain = "build -p powertrain --target thumbv7em-none-eabihf"
